export const CHANGE_SEARCHFIELD='CHANGE_SEARCHFIELD';
export const REQUEST_ROBOTS_PENDING='REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS='REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED='REQUEST_ROBOTS_FAILED';
export const REQUEST_STARWARS_PENDING='REQUEST_STARWARS_PENDING';
export const REQUEST_STARWARS_SUCCESS='REQUEST_STARWARS_SUCCESS';
export const REQUEST_STARWARS_FAILED='REQUEST_STARWARS_FAILED';